# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kate Dupon
email: ktdupon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://katedupon.com" # the base hostname & protocol for your site
github_username: kdupon

package:
  version: 0.1.0

# Custom collections
collections:
  recipes:
    output: true
    permalink: /:categories/:year/:month/:day/:title

defaults:
  - scope:
      path: ''
      type: recipes
    values:
      _hide_content: true
      layout: recipes
      title: ''
      image_path: ''
      ingredients:
        - ''
      instructions:
        - ''

helpers:
  empty_array: []

# Build settings
markdown: kramdown

exclude:
  - 'node_modules'
  - 'src/'
  - 'test/'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'package.json'
  - 'README.md'
  - 'watch.js'
  - 'webpack.config.js'
  - 'webpack.config.json'
